### create1
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"스프링클라우드",
  "email":"springcloud@a.com"
}

### create 2
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name":"스프링부트"
}

### admin create
POST http://localhost:8080/userinfos/new
Content-Type: application/json

{
"name":"adminboot",
"password":"pwd1",
"email":"admin@aa.com",
"roles":"ROLE_ADMIN,ROLE_USER"
}

### user create
POST http://localhost:8080/userinfos/new
Content-Type: application/json

{
  "name":"userboot",
  "password":"pwd2",
  "email":"user@aa.com",
  "roles":"ROLE_USER"
}

###
GET http://localhost:8080/api/users


###
GET http://localhost:8080/api/users/4

###
PATCH http://localhost:8080/api/users/spring@a.com/
Content-Type: application/json

{
  "name":"스프링3"
}

###
DELETE http://localhost:8080/api/users/1